sudo: require
language: cpp
compiler: gcc

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5

script: 
  - qmake
  - make
  - if [[ `./travis_qmake_gcc_cpp14_ubsan` != 0 ]]; then echo "UBSAN correctly detected a fail"; fi